### ISSUE TITLE
Support for client side certificate authentication

### ISSUE THREAD

**Issue by Flol0** [Kleinrotti/checkmk_telematik#1]
Hi,
just tried your Check.

where should i insert the URL which is needed? Don`t see anything, where i could insert an URL.

[special_telematik_konnektor] Agent exited with code 2: usage: agent_telematik_konnektor [-h] [-u URL] [-p PORT] [-s SSL] [-m MANDANT]
                                 [-c CLIENTSYSTEM] [-w WORKPLACE]
agent_telematik_konnektor: error: argument -u/--url: expected one argument(!!)

Thanks for the plugin!

**Comment by Kleinrotti** [comment]
The url is the IPv4 address of the Konnektor which should be set in your host in checkmk.

**Comment by Flol0** [comment]
The host in checkmk has an IPv4 address. Seems like it`s not properly attached to the agent plugin

**Comment by Flol0** [comment]
Unfortunately, this does not work. Rules deleted -> package uninstalled -> changes rolled out, package reinstalled -> package activated -> changes rolled out -> rule created. -> Changes rolled out -> same error

**Comment by Kleinrotti** [comment]
Unfortunately I can't reproduce this. It looks like multiple IP addresses are passed to the plugin, because the error says
`argument -u/--url: expected one argument(!!)` which obviously does not work.
Have you configured multiple addresses?

**Comment by Flol0** [comment]
Hi,

just one IP
![grafik](https://github.com/Kleinrotti/checkmk_telematik/assets/46406801/feb9d65c-f6f6-41f6-8e20-d5eaf76a2391)

**Comment by Kleinrotti** [comment]
Which exact CheckMK Version are you using?

**Comment by Flol0** [comment]
> Which exact CheckMK Version are you using?

i am running 2.1.0p28

**Comment by Flol0** [comment]
![grafik](https://github.com/Kleinrotti/checkmk_telematik/assets/46406801/673c3c32-2992-43f9-9003-5ac05b3ef9e0)

Hi seems like its properly called. However it`s always failing with the same error

**Comment by Flol0** [comment]
> That looks ok. Could you also execute this debug check command and upload the output (replace hostname with yours)? cmk -d hostname -vv --debug

For sure:
![grafik](https://github.com/Kleinrotti/checkmk_telematik/assets/46406801/74d49d64-7969-469a-b545-87329cf11468)

**Comment by spiritbreaker22** [comment]
Hi,

it seems the requests don't support client certificates yet. 

https://requests.readthedocs.io/en/latest/user/advanced/#client-side-certificates

The default setting for a konnektor is "force-tls" thats the way the communication is implemented with hospital information systems.

You can check the settings under Praxis -> Clientsystems -> Clientsystems-Settings

![2023-05-31 09_36_47-tls](https://github.com/Kleinrotti/checkmk_telematik/assets/77387271/4fb33295-3a57-4c8a-b53d-149f3b0e7a76)

The certificate that the special_agent needs to communicate with the konnektor can be downloaded under the Clientsystem. 

![2023-05-31 09_36_47-tls2](https://github.com/Kleinrotti/checkmk_telematik/assets/77387271/7977f39e-7b3d-412a-a0bd-e1c4c6165482)

Kind Regards

**Comment by Kleinrotti** [comment]
That could be possible that client side authentication doesn't work. Your debug output shows error code 255:
![image](https://github.com/Kleinrotti/checkmk_telematik/assets/39203164/0475037b-2db9-4788-b7ec-04417ed0e4d0)

I will release a new version 1.0.3 with a better log output today. There you should see the "real" error message then.

I don't know exactly if client side authentication is enabled in our environment. Next week I can check that. I'm currently in holidays.

**Comment by Flol0** [comment]
> Your debug output shows error code 255: ![image](https://user-images.githubusercontent.com/39203164/242256841-0475037b-2db9-4788-b7ec-04417ed0e4d0.png)
> 
> I will release a new version 1.0.3 with a better log output today. There you should see the "real" error message then.
> 
> @spiritbreaker22 That could be possible that client side authentication doesn't work. I don't know exactly if client side authentication is enabled in our environment. Next week I can check that. I'm currently in holidays.

Don't rush. Enjoy your vacation. We are not in a hurry.

**Comment by Kleinrotti** [comment]
> Don't rush. Enjoy your vacation. We are not in a hurry.

It's all fine, I'm lying with my notebook in the sun and enjoying the nice weather :)
You can get the new version [here](https://github.com/Kleinrotti/checkmk_telematik/releases/tag/1.0.3)
Hopefully with more detailed debug output. Tomorrow I will look into it if you can upload the output again.
Have a great day :)

**Comment by Flol0** [comment]
> > Don't rush. Enjoy your vacation. We are not in a hurry.
> 
> It's all fine, I'm lying with my notebook in the sun and enjoying the nice weather :) You can get the new version [here](https://github.com/Kleinrotti/checkmk_telematik/releases/tag/1.0.3) Hopefully with more detailed debug output. Tomorrow I will look into it if you can upload the output again. Have a great day :)

Hope this helps:
![grafik](https://github.com/Kleinrotti/checkmk_telematik/assets/46406801/db0bc363-b9a8-4d93-9e87-e3f8024d5580)

**Comment by Kleinrotti** [comment]
Thanks @Flol0, this seems like the same problem @spiritbreaker22 had.
I will work on a new release next week which provides an option to use a client certificate for authentication.
