### ISSUE TITLE
SecuNet no connection

### ISSUE THREAD

**Issue by unclesam87** [Kleinrotti/checkmk_telematik#9]
hey, 
i am trying to monitor an secunet konnektor 
Produkt-TypKonnektor PTV5
Produkt-Typ-Version5.1.0
Produktsecunet konnektor 2.0.0

u wrote that i should enable remote monitoring, i can only find an option for remote administration - is it the same?
or did i miss an option?
thx!

**Comment by Kleinrotti** [comment]
I'm not sure if remote administration is the same.
But I recommend to test the agent with the --debug flag in the console to get further information of errors.
